apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus 
  labels:
    id: nexuspv
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs :
    path: "/var/nfsshare"
    server: 192.168.0.6
