apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  labels:
    app: nexus
spec:
  type: NodePort
  ports:
    - name: nexus
      port: 8081
      protocol: TCP
      targetPort: 8081  
  selector:
    app: nexus
